

[[dependencies]]
  target = "{{ .ModuleWithPathToProtoDir }}"
  branch = "{{ .Branch }}"
  path = "client/{{ .ClientNameSnakeCase }}"
  includes = [
    "{{ .PtotoFileName }}",
  ]
  protocol = "https"